const fs = require('fs');
const path = require('path');
const { p, writeCountry } = require('./player_builder_base.cjs');

console.log('Generating complete database for all 20 countries with 30-35 players per country...');

// We create the files directly using robust helper functions to guarantee each country has 32-35 players.

function generateNations() {
  // 1. Bangladesh
  const BAN_PLAYERS = [
    // Legendary (81-90)
    p('ban_shakib_al_hasan', 'Shakib Al Hasan', 'Shakib Al Hasan', 'Bangladesh', 'BAN', 37, '1987-03-24', 'Active', 'LEGENDARY', 89, 'All-Rounder', 'Left-Arm Spin All-Rounder', 'Left-hand bat', 'Slow left-arm orthodox',
      { battingAbility: 90, technique: 92, timing: 90, power: 84, shotSelection: 92, strikeRotation: 94, runningBetweenWickets: 92 },
      { bowlingAbility: 94, pace: 50, accuracy: 96, swing: 15, seam: 15, spin: 94, variation: 92, control: 96 },
      { fielding: 88, catching: 90, throwing: 88, groundFielding: 88, reaction: 90 }, null,
      'Dhaka Dynamites / Surrey', 'Bangladesh Premier League', 4500, 900,
      { matches: 447, runs: 14720, highestScore: 217, battingAverage: 35.5, strikeRate: 82.0, hundreds: 14, fifties: 99, wickets: 712, bowlingAverage: 28.2, economyRate: 3.8, bestBowling: '7/36', catches: 185, stumpings: 0 },
      ['All-Time Greatest All-Rounder in Bangladesh Cricket History', 'Fastest to 6,000 runs and 300 wickets in ODIs', 'Over a decade as #1 ICC All-Rounder across all formats', '606 runs & 11 wickets in 2019 World Cup']),

    p('ban_tamim_iqbal', 'Tamim Iqbal', 'Tamim Iqbal', 'Bangladesh', 'BAN', 35, '1989-03-20', 'Retired', 'LEGENDARY', 87, 'Batter', 'Opening Batter', 'Left-hand bat', 'Right-arm off break',
      { battingAbility: 92, technique: 90, timing: 92, power: 88, shotSelection: 88, strikeRotation: 86, runningBetweenWickets: 85 },
      { bowlingAbility: 15, pace: 25, accuracy: 25, swing: 15, seam: 15, spin: 20, variation: 15, control: 20 },
      { fielding: 82, catching: 86, throwing: 84, groundFielding: 80, reaction: 82 }, null,
      'Fortune Barishal (BPL Champion Captain)', 'Bangladesh Premier League', 3800, 760,
      { matches: 389, runs: 15192, highestScore: 206, battingAverage: 36.8, strikeRate: 78.0, hundreds: 25, fifties: 94, wickets: 0, bowlingAverage: 0, economyRate: 0, bestBowling: '0/0', catches: 142, stumpings: 0 },
      ['All-Time Leading International Run Scorer for Bangladesh (15,192 runs)', 'First Bangladeshi to score 10,000 international runs', 'Centuries in all three international formats', 'Lord\'s Honours Board Centurion (103 in 2010)']),

    p('ban_mushfiqur_rahim', 'Mushfiqur Rahim', 'Mushfiqur Rahim', 'Bangladesh', 'BAN', 37, '1987-05-09', 'Active', 'LEGENDARY', 87, 'Wicketkeeper-Batter', 'Middle-Order Anchor WK-Batter', 'Right-hand bat', 'Right-arm medium',
      { battingAbility: 90, technique: 92, timing: 90, power: 78, shotSelection: 92, strikeRotation: 92, runningBetweenWickets: 92 },
      { bowlingAbility: 10, pace: 20, accuracy: 15, swing: 10, seam: 10, spin: 15, variation: 15, control: 15 },
      { fielding: 90, catching: 92, throwing: 88, groundFielding: 88, reaction: 92 },
      { wicketkeeping: 92, catching: 94, stumping: 92, reflexes: 94 },
      'Dhaka Capitals', 'Bangladesh Premier League', 3700, 740,
      { matches: 458, runs: 15050, highestScore: 219, battingAverage: 37.5, strikeRate: 79.0, hundreds: 19, fifties: 80, wickets: 0, bowlingAverage: 0, economyRate: 0, bestBowling: '0/0', catches: 440, stumpings: 98 },
      ['First Bangladeshi to score a Test Double Century (219* vs ZIM & 200 vs SL)', 'Most Matches Played for Bangladesh (450+ matches)', 'Historic 191 in Pakistan Test Series Victory 2024']),

    p('ban_mashrafe_mortaza', 'Mashrafe Mortaza', 'Mashrafe Mortaza (Narail Express)', 'Bangladesh', 'BAN', 40, '1983-10-05', 'Retired', 'LEGENDARY', 86, 'Bowler', 'Fast-Medium & Greatest Leader', 'Right-hand bat', 'Right-arm fast-medium',
      { battingAbility: 68, technique: 62, timing: 68, power: 85, shotSelection: 65, strikeRotation: 68, runningBetweenWickets: 70 },
      { bowlingAbility: 90, pace: 84, accuracy: 92, swing: 88, seam: 90, spin: 15, variation: 86, control: 92 },
      { fielding: 84, catching: 88, throwing: 86, groundFielding: 82, reaction: 84 }, null,
      'Sylhet Strikers', 'Bangladesh Premier League', 3600, 720,
      { matches: 310, runs: 2950, highestScore: 79, battingAverage: 18.0, strikeRate: 85.0, hundreds: 0, fifties: 4, wickets: 390, bowlingAverage: 31.5, economyRate: 4.7, bestBowling: '6/26', catches: 95, stumpings: 0 },
      ['Most Successful ODI Captain in Bangladesh History (50 wins in 88 matches)', 'Led Bangladesh to 2015 World Cup Quarter-Finals & 2017 Champions Trophy Semi-Finals', '4-Time BPL Winning Captain']),

    p('ban_mahmudullah_riyad', 'Mahmudullah Riyad', 'Mahmudullah (Silent Killer)', 'Bangladesh', 'BAN', 38, '1986-02-04', 'Active', 'LEGENDARY', 85, 'All-Rounder', 'Off Spin & Clutch Finisher', 'Right-hand bat', 'Right-arm off break',
      { battingAbility: 86, technique: 86, timing: 88, power: 86, shotSelection: 88, strikeRotation: 88, runningBetweenWickets: 88 },
      { bowlingAbility: 75, pace: 45, accuracy: 82, swing: 15, seam: 15, spin: 80, variation: 76, control: 82 },
      { fielding: 90, catching: 94, throwing: 88, groundFielding: 88, reaction: 90 }, null,
      'Fortune Barishal', 'Bangladesh Premier League', 3400, 680,
      { matches: 412, runs: 10600, highestScore: 150, battingAverage: 34.0, strikeRate: 80.0, hundreds: 9, fifties: 54, wickets: 165, bowlingAverage: 42.0, economyRate: 4.9, bestBowling: '5/51', catches: 168, stumpings: 0 },
      ['First Bangladeshi to score a World Cup Century (Back-to-back vs ENG & NZ 2015)', 'Clutch Finisher with 111 vs South Africa in 2023 World Cup', '"Silent Killer" - Most reliable middle-order savior']),

    // Superstar (71-80)
    p('ban_mustafizur_rahman', 'Mustafizur Rahman', 'Mustafizur Rahman (The Fizz)', 'Bangladesh', 'BAN', 28, '1995-09-06', 'Active', 'SUPERSTAR', 80, 'Bowler', 'Left-Arm Cutter Magician', 'Left-hand bat', 'Left-arm fast-medium',
      { battingAbility: 25, technique: 20, timing: 25, power: 45, shotSelection: 22, strikeRotation: 25, runningBetweenWickets: 55 },
      { bowlingAbility: 94, pace: 86, accuracy: 92, swing: 80, seam: 85, spin: 15, variation: 99, control: 92 },
      { fielding: 86, catching: 88, throwing: 88, groundFielding: 85, reaction: 88 }, null,
      'Chennai Super Kings / Comilla Victorians', 'Indian Premier League', 4200, 840,
      { matches: 250, runs: 280, highestScore: 20, battingAverage: 6.5, strikeRate: 58.0, hundreds: 0, fifties: 0, wickets: 360, bowlingAverage: 23.0, economyRate: 4.8, bestBowling: '6/43', catches: 45, stumpings: 0 },
      ['World-renowned Off-Cutter and Slower Ball Specialist', 'Record 11 wickets in first two career ODIs vs India (5/50 & 6/43)', 'IPL Emerging Player of the Year 2016 with Sunrisers Hyderabad', '14 wickets in IPL 2024 for CSK']),

    p('ban_taskin_ahmed', 'Taskin Ahmed', 'Taskin Ahmed', 'Bangladesh', 'BAN', 29, '1995-04-03', 'Active', 'SUPERSTAR', 79, 'Bowler', 'Express Fast Bowler (Pace & Bounce)', 'Left-hand bat', 'Right-arm fast',
      { battingAbility: 35, technique: 30, timing: 35, power: 65, shotSelection: 30, strikeRotation: 35, runningBetweenWickets: 65 },
      { bowlingAbility: 90, pace: 94, accuracy: 88, swing: 88, seam: 92, spin: 10, variation: 84, control: 88 },
      { fielding: 88, catching: 90, throwing: 92, groundFielding: 88, reaction: 90 }, null,
      'Dhaka Capitals (BPL Icon)', 'Bangladesh Premier League', 4000, 800,
      { matches: 165, runs: 650, highestScore: 75, battingAverage: 12.0, strikeRate: 78.0, hundreds: 0, fifties: 1, wickets: 248, bowlingAverage: 28.5, economyRate: 5.1, bestBowling: '5/28', catches: 38, stumpings: 0 },
      ['Leader of the Bangladesh Pace Revolution (145+ km/h)', '5-wicket haul on ODI debut vs India (5/28)', 'Player of the Series in Historic 2-1 ODI Series Win in South Africa 2022', 'Vice-Captain in 2024 T20 World Cup']),

    p('ban_mehidy_hasan_miraz', 'Mehidy Hasan Miraz', 'Mehidy Hasan Miraz', 'Bangladesh', 'BAN', 26, '1997-10-25', 'Active', 'SUPERSTAR', 79, 'All-Rounder', 'Off Spin All-Rounder & Test MVP', 'Right-hand bat', 'Right-arm off break',
      { battingAbility: 84, technique: 86, timing: 85, power: 80, shotSelection: 84, strikeRotation: 86, runningBetweenWickets: 90 },
      { bowlingAbility: 89, pace: 50, accuracy: 94, swing: 15, seam: 15, spin: 90, variation: 86, control: 94 },
      { fielding: 94, catching: 96, throwing: 92, groundFielding: 94, reaction: 95 }, null,
      'Khulna Tigers / Bangladesh Vice-Captain', 'Bangladesh Premier League', 4100, 820,
      { matches: 195, runs: 3800, highestScore: 112, battingAverage: 28.0, strikeRate: 78.0, hundreds: 3, fifties: 18, wickets: 295, bowlingAverage: 30.5, economyRate: 3.7, bestBowling: '7/58', catches: 88, stumpings: 0 },
      ['Player of the Series in historic 2-0 Test Series Sweep in Pakistan 2024 (155 runs & 10 wickets)', '19 wickets in debut Test series vs England in 2016', 'Unbeaten 100* & 38* in historic ODI series comeback win vs India 2022']),

    p('ban_litton_das', 'Litton Das', 'Litton Das', 'Bangladesh', 'BAN', 29, '1994-10-13', 'Active', 'SUPERSTAR', 79, 'Wicketkeeper-Batter', 'Silken Stroke Maker & Opener', 'Right-hand bat', 'Right-arm off break',
      { battingAbility: 90, technique: 94, timing: 96, power: 84, shotSelection: 88, strikeRotation: 90, runningBetweenWickets: 92 },
      { bowlingAbility: 10, pace: 20, accuracy: 15, swing: 10, seam: 10, spin: 15, variation: 15, control: 15 },
      { fielding: 94, catching: 96, throwing: 92, groundFielding: 94, reaction: 96 },
      { wicketkeeping: 94, catching: 96, stumping: 94, reflexes: 96 },
      'Comilla Victorians / Kolkata Knight Riders', 'Bangladesh Premier League', 3900, 780,
      { matches: 215, runs: 6900, highestScore: 176, battingAverage: 34.5, strikeRate: 85.0, hundreds: 11, fifties: 36, wickets: 0, bowlingAverage: 0, economyRate: 0, bestBowling: '0/0', catches: 180, stumpings: 35 },
      ['Highest Individual Score in Bangladesh ODI History (176 vs Zimbabwe)', 'Heroic 138 from 26/6 in 2nd Test vs Pakistan in Rawalpindi 2024', 'Fastest 50 in T20 World Cup for Bangladesh (21 balls vs India in Adelaide 2022)']),

    p('ban_shoriful_islam', 'Shoriful Islam', 'Shoriful Islam', 'Bangladesh', 'BAN', 23, '2001-06-03', 'Active', 'SUPERSTAR', 78, 'Bowler', 'Left-Arm Fast Seamer (Bounce & Movement)', 'Left-hand bat', 'Left-arm medium-fast',
      { battingAbility: 30, technique: 25, timing: 30, power: 60, shotSelection: 28, strikeRotation: 30, runningBetweenWickets: 60 },
      { bowlingAbility: 88, pace: 90, accuracy: 88, swing: 92, seam: 90, spin: 10, variation: 86, control: 88 },
      { fielding: 86, catching: 88, throwing: 90, groundFielding: 86, reaction: 88 }, null,
      'Rangpur Riders', 'Bangladesh Premier League', 3700, 740,
      { matches: 85, runs: 180, highestScore: 26, battingAverage: 8.5, strikeRate: 65.0, hundreds: 0, fifties: 0, wickets: 138, bowlingAverage: 24.5, economyRate: 5.1, bestBowling: '5/22', catches: 24, stumpings: 0 },
      ['Under-19 World Cup Champion 2020 (Key Striker in Final vs India)', 'Top Wicket-Taker in BPL 2024 (22 wickets including a Hat-trick)', 'Tall 6ft 3in Left-Arm Inswinger Specialist']),

    p('ban_towhid_hridoy', 'Towhid Hridoy', 'Towhid Hridoy', 'Bangladesh', 'BAN', 23, '2000-12-04', 'Active', 'SUPERSTAR', 78, 'Batter', 'Middle-Order Dynamic Strokeplayer', 'Right-hand bat', 'Right-arm off break',
      { battingAbility: 88, technique: 86, timing: 92, power: 90, shotSelection: 86, strikeRotation: 88, runningBetweenWickets: 92 },
      { bowlingAbility: 20, pace: 25, accuracy: 25, swing: 15, seam: 15, spin: 30, variation: 20, control: 25 },
      { fielding: 92, catching: 95, throwing: 92, groundFielding: 92, reaction: 94 }, null,
      'Comilla Victorians', 'Bangladesh Premier League', 3800, 760,
      { matches: 62, runs: 1650, highestScore: 108, battingAverage: 35.0, strikeRate: 110.0, hundreds: 1, fifties: 10, wickets: 0, bowlingAverage: 0, economyRate: 0, bestBowling: '0/0', catches: 36, stumpings: 0 },
      ['Highest Run-Scorer for Bangladesh in 2024 ICC T20 World Cup', 'Under-19 World Cup Champion 2020 (Vice-Captain)', 'Sensational 92 on ODI debut vs Ireland in Sylhet']),

    p('ban_rishad_hossain', 'Rishad Hossain', 'Rishad Hossain', 'Bangladesh', 'BAN', 22, '2002-07-15', 'Active', 'SUPERSTAR', 77, 'Bowler', 'Tall Right-Arm Leg Spinner & Big Hitter', 'Right-hand bat', 'Right-arm leg break',
      { battingAbility: 65, technique: 58, timing: 68, power: 88, shotSelection: 62, strikeRotation: 65, runningBetweenWickets: 78 },
      { bowlingAbility: 88, pace: 56, accuracy: 88, swing: 15, seam: 15, spin: 92, variation: 94, control: 88 },
      { fielding: 90, catching: 94, throwing: 92, groundFielding: 90, reaction: 92 }, null,
      'Comilla Victorians / Big Bash League Prospect', 'Bangladesh Premier League', 3800, 760,
      { matches: 38, runs: 340, highestScore: 48, battingAverage: 18.0, strikeRate: 145.0, hundreds: 0, fifties: 0, wickets: 58, bowlingAverage: 19.5, economyRate: 6.8, bestBowling: '3/22', catches: 22, stumpings: 0 },
      ['Breakout Star of 2024 ICC T20 World Cup (14 wickets — 3rd Highest in the World)', '3/22 vs Sri Lanka in Dallas & 3/32 vs Australia in Antigua', '6ft 3in Height Extracting Sharp Bounce and Leg-Spin Turn', 'Hit 3 consecutive sixes in ODI vs Sri Lanka in Chattogram']),

    p('ban_tanzid_hasan_tamim', 'Tanzid Hasan Tamim', 'Tanzid Hasan', 'Bangladesh', 'BAN', 23, '2000-12-01', 'Active', 'SUPERSTAR', 77, 'Batter', 'Attacking Left-Handed Opener', 'Left-hand bat', 'Right-arm leg break',
      { battingAbility: 86, technique: 84, timing: 90, power: 88, shotSelection: 84, strikeRotation: 84, runningBetweenWickets: 92 },
      { bowlingAbility: 15, pace: 25, accuracy: 20, swing: 15, seam: 15, spin: 25, variation: 20, control: 20 },
      { fielding: 90, catching: 94, throwing: 90, groundFielding: 90, reaction: 92 }, null,
      'Chattogram Challengers', 'Bangladesh Premier League', 3400, 680,
      { matches: 42, runs: 980, highestScore: 116, battingAverage: 28.5, strikeRate: 118.0, hundreds: 1, fifties: 6, wickets: 0, bowlingAverage: 0, economyRate: 0, bestBowling: '0/0', catches: 25, stumpings: 0 },
      ['Under-19 World Cup Champion 2020 Leading Opener', 'Blistering 84 off 81 vs India in Pune 2023 World Cup', 'Century in BPL 2024 (116 off 65 balls)']),

    p('ban_najmul_hossain_shanto', 'Najmul Hossain Shanto', 'N. H. Shanto', 'Bangladesh', 'BAN', 25, '1998-08-25', 'Active', 'SUPERSTAR', 78, 'Batter', 'Top-Order Classical Batter & All-Format Captain', 'Left-hand bat', 'Right-arm off break',
      { battingAbility: 86, technique: 88, timing: 88, power: 82, shotSelection: 86, strikeRotation: 88, runningBetweenWickets: 90 },
      { bowlingAbility: 35, pace: 40, accuracy: 45, swing: 15, seam: 15, spin: 45, variation: 35, control: 45 },
      { fielding: 94, catching: 96, throwing: 92, groundFielding: 94, reaction: 95 }, null,
      'Sylhet Strikers / Bangladesh National Captain', 'Bangladesh Premier League', 3900, 780,
      { matches: 155, runs: 4400, highestScore: 163, battingAverage: 32.5, strikeRate: 78.0, hundreds: 7, fifties: 22, wickets: 2, bowlingAverage: 45.0, economyRate: 5.2, bestBowling: '1/10', catches: 84, stumpings: 0 },
      ['Captain who led Bangladesh to historic 2-0 Test Series Clean Sweep in Pakistan 2024', 'Twin Centuries in a single Test vs Afghanistan 2023 (146 & 124)', 'Leading Run-Scorer for Bangladesh in 2023 ODI World Cup']),

    // Star (61-70) - 21 players
    p('ban_soumya_sarkar', 'Soumya Sarkar', 'Soumya Sarkar', 'Bangladesh', 'BAN', 31, '1993-02-25', 'Active', 'STAR', 70, 'All-Rounder', 'Top-Order Power Opener & Medium Pacer', 'Left-hand bat', 'Right-arm medium',
      { battingAbility: 84, technique: 80, timing: 88, power: 90, shotSelection: 80, strikeRotation: 80, runningBetweenWickets: 86 },
      { bowlingAbility: 74, pace: 76, accuracy: 78, swing: 80, seam: 76, spin: 15, variation: 80, control: 78 },
      { fielding: 90, catching: 94, throwing: 90, groundFielding: 88, reaction: 92 }, null,
      'Fortune Barishal', 'Bangladesh Premier League', 2600, 520,
      { matches: 168, runs: 4200, highestScore: 169, battingAverage: 28.0, strikeRate: 92.0, hundreds: 4, fifties: 20, wickets: 58, bowlingAverage: 35.0, economyRate: 5.5, bestBowling: '3/18', catches: 82, stumpings: 0 },
      ['Sensational 169 in New Zealand (Nelson 2023) — Highest ODI score by an Asian in NZ', 'Match-winning 127* vs South Africa in 2015', 'Safe Catcher in the Deep and Slips']),

    p('ban_taijul_islam', 'Taijul Islam', 'Taijul Islam', 'Bangladesh', 'BAN', 32, '1992-02-07', 'Active', 'STAR', 70, 'Bowler', 'Left-Arm Classical Test Spin Master', 'Left-hand bat', 'Slow left-arm orthodox',
      { battingAbility: 38, technique: 38, timing: 38, power: 45, shotSelection: 38, strikeRotation: 40, runningBetweenWickets: 60 },
      { bowlingAbility: 88, pace: 48, accuracy: 96, swing: 15, seam: 15, spin: 90, variation: 88, control: 96 },
      { fielding: 84, catching: 88, throwing: 84, groundFielding: 84, reaction: 86 }, null,
      'Fortune Barishal', 'Bangladesh Premier League', 2500, 500,
      { matches: 75, runs: 750, highestScore: 47, battingAverage: 11.5, strikeRate: 42.0, hundreds: 0, fifties: 0, wickets: 235, bowlingAverage: 31.0, economyRate: 3.1, bestBowling: '8/39', catches: 35, stumpings: 0 },
      ['200+ Test Wickets for Bangladesh (2nd Highest in History)', 'Hat-trick on ODI Debut vs Zimbabwe (First in Cricket History)', '8/39 vs Zimbabwe in Mirpur (Bangladesh Best Test Bowling in History)']),

    p('ban_hasan_mahmud', 'Hasan Mahmud', 'Hasan Mahmud', 'Bangladesh', 'BAN', 24, '1999-10-12', 'Active', 'STAR', 70, 'Bowler', 'Skiddy Fast Bowler (Accurate Outswing)', 'Right-hand bat', 'Right-arm fast-medium',
      { battingAbility: 32, technique: 28, timing: 32, power: 55, shotSelection: 28, strikeRotation: 30, runningBetweenWickets: 60 },
      { bowlingAbility: 86, pace: 90, accuracy: 90, swing: 94, seam: 88, spin: 10, variation: 84, control: 90 },
      { fielding: 88, catching: 90, throwing: 90, groundFielding: 88, reaction: 90 }, null,
      'Rangpur Riders', 'Bangladesh Premier League', 2800, 560,
      { matches: 58, runs: 120, highestScore: 22, battingAverage: 8.0, strikeRate: 65.0, hundreds: 0, fifties: 0, wickets: 85, bowlingAverage: 24.0, economyRate: 4.9, bestBowling: '5/43', catches: 18, stumpings: 0 },
      ['Historic 5-fer in Pakistan (5/43 in 2nd Test in Rawalpindi 2024 to seal 2-0 Series Win)', '5/34 vs India in Chennai Test 2024 (Dismissed Rohit, Kohli, Gill, Pant)', 'Pristine Seam Position and Late Away Movement']),

    p('ban_tanzim_hasan_sakib', 'Tanzim Hasan Sakib', 'Tanzim Hasan Sakib', 'Bangladesh', 'BAN', 21, '2002-10-20', 'Active', 'STAR', 70, 'Bowler', 'Fiery Pace & Inswing Striker', 'Right-hand bat', 'Right-arm medium-fast',
      { battingAbility: 45, technique: 38, timing: 45, power: 75, shotSelection: 40, strikeRotation: 40, runningBetweenWickets: 68 },
      { bowlingAbility: 86, pace: 90, accuracy: 86, swing: 92, seam: 88, spin: 10, variation: 88, control: 86 },
      { fielding: 92, catching: 95, throwing: 94, groundFielding: 92, reaction: 94 }, null,
      'Sylhet Strikers', 'Bangladesh Premier League', 2700, 540,
      { matches: 32, runs: 180, highestScore: 35, battingAverage: 15.0, strikeRate: 95.0, hundreds: 0, fifties: 0, wickets: 45, bowlingAverage: 20.5, economyRate: 5.6, bestBowling: '4/7', catches: 15, stumpings: 0 },
      ['4/7 vs Nepal in 2024 ICC T20 World Cup with 21 Dot Balls (World Cup Record)', 'Dismissed Rohit Sharma with Inswinger on 2nd ball of ODI Debut vs India in Asia Cup 2023', 'Under-19 World Cup Champion 2020']),

    p('ban_mahedi_hasan', 'Mahedi Hasan', 'Mahedi Hasan', 'Bangladesh', 'BAN', 29, '1994-12-12', 'Active', 'STAR', 69, 'All-Rounder', 'Powerplay Off-Spin Specialist & Power Hitter', 'Right-hand bat', 'Right-arm off break',
      { battingAbility: 76, technique: 72, timing: 78, power: 84, shotSelection: 74, strikeRotation: 78, runningBetweenWickets: 86 },
      { bowlingAbility: 84, pace: 52, accuracy: 94, swing: 15, seam: 15, spin: 85, variation: 82, control: 94 },
      { fielding: 92, catching: 95, throwing: 92, groundFielding: 92, reaction: 94 }, null,
      'Rangpur Riders', 'Bangladesh Premier League', 2300, 460,
      { matches: 78, runs: 850, highestScore: 51, battingAverage: 20.0, strikeRate: 120.0, hundreds: 0, fifties: 1, wickets: 82, bowlingAverage: 25.0, economyRate: 5.5, bestBowling: '4/25', catches: 35, stumpings: 0 },
      ['Stifling Powerplay Bowler with Career Economy under 6.5 in T20s', 'Top Performer in BPL for multiple seasons']),

    p('ban_nasum_ahmed', 'Nasum Ahmed', 'Nasum Ahmed', 'Bangladesh', 'BAN', 29, '1994-12-05', 'Active', 'STAR', 68, 'Bowler', 'Left-Arm Orthodox Stifler', 'Left-hand bat', 'Slow left-arm orthodox',
      { battingAbility: 52, technique: 45, timing: 52, power: 72, shotSelection: 48, strikeRotation: 50, runningBetweenWickets: 68 },
      { bowlingAbility: 82, pace: 50, accuracy: 92, swing: 15, seam: 15, spin: 84, variation: 80, control: 92 },
      { fielding: 84, catching: 88, throwing: 84, groundFielding: 84, reaction: 86 }, null,
      'Chattogram Challengers', 'Bangladesh Premier League', 1900, 380,
      { matches: 62, runs: 320, highestScore: 44, battingAverage: 14.0, strikeRate: 85.0, hundreds: 0, fifties: 0, wickets: 68, bowlingAverage: 26.5, economyRate: 5.2, bestBowling: '4/10', catches: 18, stumpings: 0 },
      ['4/10 vs Australia in T20I Series Win 2021', 'Crucial 44 & 3/30 vs India in Asia Cup 2023 Win']),

    p('ban_jaker_ali_anik', 'Jaker Ali Anik', 'Jaker Ali', 'Bangladesh', 'BAN', 26, '1998-02-22', 'Active', 'STAR', 68, 'Wicketkeeper-Batter', 'Death-Overs Power Finisher', 'Right-hand bat', 'Right-arm off break',
      { battingAbility: 82, technique: 78, timing: 85, power: 92, shotSelection: 80, strikeRotation: 82, runningBetweenWickets: 88 },
      { bowlingAbility: 10, pace: 20, accuracy: 15, swing: 10, seam: 10, spin: 15, variation: 15, control: 15 },
      { fielding: 88, catching: 92, throwing: 88, groundFielding: 88, reaction: 90 },
      { wicketkeeping: 88, catching: 90, stumping: 88, reflexes: 90 },
      'Comilla Victorians', 'Bangladesh Premier League', 2000, 400,
      { matches: 25, runs: 480, highestScore: 68, battingAverage: 34.0, strikeRate: 142.0, hundreds: 0, fifties: 3, wickets: 0, bowlingAverage: 0, economyRate: 0, bestBowling: '0/0', catches: 18, stumpings: 4 },
      ['Blistering 68 off 34 balls vs Sri Lanka in Sylhet T20I (6 Sixes)', '3-Time BPL Champion with Comilla Victorians', 'Clutch Finisher in Test Match vs South Africa (58 in Mirpur 2024)']),

    p('ban_mohammad_naim', 'Mohammad Naim Sheikh', 'Naim Sheikh', 'Bangladesh', 'BAN', 25, '1999-08-22', 'Active', 'STAR', 67, 'Batter', 'Top-Order Left-Handed Batter', 'Left-hand bat', 'Right-arm medium',
      { battingAbility: 80, technique: 78, timing: 82, power: 84, shotSelection: 76, strikeRotation: 78, runningBetweenWickets: 86 },
      { bowlingAbility: 15, pace: 25, accuracy: 20, swing: 15, seam: 15, spin: 20, variation: 15, control: 20 },
      { fielding: 86, catching: 90, throwing: 88, groundFielding: 86, reaction: 88 }, null,
      'Dhaka Capitals', 'Bangladesh Premier League', 1800, 360,
      { matches: 45, runs: 1100, highestScore: 81, battingAverage: 27.0, strikeRate: 110.0, hundreds: 0, fifties: 6, wickets: 0, bowlingAverage: 0, economyRate: 0, bestBowling: '0/0', catches: 22, stumpings: 0 },
      ['Sensational 81 off 48 balls vs India in Nagpur T20I 2019', 'Top Run-Scorer in Dhaka Premier League (DPL) multiple seasons']),

    p('ban_anamul_haque_bijoy', 'Anamul Haque Bijoy', 'Anamul Haque', 'Bangladesh', 'BAN', 31, '1992-12-16', 'Active', 'STAR', 67, 'Wicketkeeper-Batter', 'Aggressive Top-Order WK-Batter', 'Right-hand bat', 'Right-arm off break',
      { battingAbility: 80, technique: 78, timing: 84, power: 82, shotSelection: 76, strikeRotation: 78, runningBetweenWickets: 84 },
      { bowlingAbility: 10, pace: 20, accuracy: 15, swing: 10, seam: 10, spin: 15, variation: 15, control: 15 },
      { fielding: 86, catching: 90, throwing: 86, groundFielding: 86, reaction: 88 },
      { wicketkeeping: 88, catching: 90, stumping: 88, reflexes: 88 },
      'Khulna Tigers', 'Bangladesh Premier League', 1700, 340,
      { matches: 75, runs: 2150, highestScore: 120, battingAverage: 30.0, strikeRate: 75.0, hundreds: 3, fifties: 9, wickets: 0, bowlingAverage: 0, economyRate: 0, bestBowling: '0/0', catches: 45, stumpings: 8 },
      ['First Bangladeshi to score 1,000+ runs in a single List-A tournament (1,138 runs in DPL 2022)', 'Century vs West Indies in Khulna (120)']),

    p('ban_afif_hossain', 'Afif Hossain Dhrubo', 'Afif Hossain', 'Bangladesh', 'BAN', 24, '1999-09-22', 'Active', 'STAR', 68, 'All-Rounder', 'Left-Handed Strokeplayer & Off Spinner', 'Left-hand bat', 'Right-arm off break',
      { battingAbility: 80, technique: 82, timing: 86, power: 80, shotSelection: 80, strikeRotation: 84, runningBetweenWickets: 90 },
      { bowlingAbility: 70, pace: 48, accuracy: 78, swing: 15, seam: 15, spin: 75, variation: 70, control: 78 },
      { fielding: 92, catching: 95, throwing: 92, groundFielding: 92, reaction: 94 }, null,
      'Khulna Tigers', 'Bangladesh Premier League', 2200, 440,
      { matches: 95, runs: 1850, highestScore: 93, battingAverage: 26.5, strikeRate: 118.0, hundreds: 0, fifties: 8, wickets: 25, bowlingAverage: 32.0, economyRate: 6.2, bestBowling: '5/21', catches: 42, stumpings: 0 },
      ['Unbeaten 93* from 45/6 vs Afghanistan in Chattogram ODI to pull off miraculous win', '5/21 on BPL debut as a 17-year-old (Youngest in BPL History)']),

    p('ban_shamim_hossain_patwary', 'Shamim Hossain', 'Shamim Hossain', 'Bangladesh', 'BAN', 23, '2000-09-02', 'Active', 'STAR', 67, 'All-Rounder', 'Electric Fielder & Lower-Order Power Hitter', 'Left-hand bat', 'Right-arm off break',
      { battingAbility: 78, technique: 74, timing: 82, power: 88, shotSelection: 76, strikeRotation: 80, runningBetweenWickets: 94 },
      { bowlingAbility: 65, pace: 45, accuracy: 74, swing: 15, seam: 15, spin: 70, variation: 65, control: 74 },
      { fielding: 98, catching: 98, throwing: 98, groundFielding: 98, reaction: 98 }, null,
      'Rangpur Riders', 'Bangladesh Premier League', 1900, 380,
      { matches: 42, runs: 650, highestScore: 51, battingAverage: 24.0, strikeRate: 135.0, hundreds: 0, fifties: 1, wickets: 6, bowlingAverage: 35.0, economyRate: 7.0, bestBowling: '2/18', catches: 35, stumpings: 0 },
      ['Widely regarded as Bangladesh\'s #1 acrobatic backward-point fielder', 'Under-19 World Cup Champion 2020']),

    p('ban_khaled_ahmed', 'Khaled Ahmed', 'Khaled Ahmed', 'Bangladesh', 'BAN', 31, '1992-09-20', 'Active', 'STAR', 67, 'Bowler', 'Tall Hit-the-Deck Test Seamer', 'Right-hand bat', 'Right-arm fast-medium',
      { battingAbility: 20, technique: 15, timing: 20, power: 45, shotSelection: 18, strikeRotation: 20, runningBetweenWickets: 50 },
      { bowlingAbility: 82, pace: 88, accuracy: 85, swing: 80, seam: 88, spin: 10, variation: 78, control: 85 },
      { fielding: 80, catching: 84, throwing: 85, groundFielding: 80, reaction: 82 }, null,
      'Fortune Barishal', 'Bangladesh Premier League', 1600, 320,
      { matches: 22, runs: 45, highestScore: 12, battingAverage: 4.5, strikeRate: 35.0, hundreds: 0, fifties: 0, wickets: 42, bowlingAverage: 33.0, economyRate: 3.4, bestBowling: '5/106', catches: 8, stumpings: 0 },
      ['5-wicket haul vs South Africa in Gqeberha (Port Elizabeth) 2022', 'Disciplined test length workhorse']),

    p('ban_ebadot_hossain', 'Ebadot Hossain Chowdhury', 'Ebadot Hossain (Air Force Salute)', 'Bangladesh', 'BAN', 30, '1994-01-07', 'Active', 'STAR', 69, 'Bowler', 'Express Fast Bowler & Mount Maunganui Hero', 'Right-hand bat', 'Right-arm fast',
      { battingAbility: 18, technique: 12, timing: 18, power: 45, shotSelection: 15, strikeRotation: 18, runningBetweenWickets: 55 },
      { bowlingAbility: 86, pace: 94, accuracy: 84, swing: 86, seam: 88, spin: 10, variation: 82, control: 84 },
      { fielding: 84, catching: 86, throwing: 90, groundFielding: 84, reaction: 86 }, null,
      'Sylhet Strikers / Bangladesh Air Force', 'Bangladesh Premier League', 2400, 480,
      { matches: 45, runs: 65, highestScore: 21, battingAverage: 5.0, strikeRate: 50.0, hundreds: 0, fifties: 0, wickets: 78, bowlingAverage: 29.5, economyRate: 4.6, bestBowling: '6/46', catches: 15, stumpings: 0 },
      ['Architect of Mount Maunganui Miracle (6/46 vs World Test Champions New Zealand in 2022)', 'Iconic Bangladesh Air Force Trademark Salute Celebration', '140+ km/h Reverse Swing Master']),

    p('ban_mohammad_saifuddin', 'Mohammad Saifuddin', 'Mohammad Saifuddin', 'Bangladesh', 'BAN', 27, '1996-11-01', 'Active', 'STAR', 68, 'All-Rounder', 'Pace Bowling All-Rounder & Yorker Specialist', 'Left-hand bat', 'Right-arm medium-fast',
      { battingAbility: 78, technique: 72, timing: 80, power: 88, shotSelection: 76, strikeRotation: 78, runningBetweenWickets: 84 },
      { bowlingAbility: 82, pace: 84, accuracy: 85, swing: 84, seam: 80, spin: 10, variation: 88, control: 85 },
      { fielding: 86, catching: 90, throwing: 88, groundFielding: 86, reaction: 88 }, null,
      'Dhaka Capitals', 'Bangladesh Premier League', 2100, 420,
      { matches: 75, runs: 850, highestScore: 51, battingAverage: 24.0, strikeRate: 122.0, hundreds: 0, fifties: 2, wickets: 88, bowlingAverage: 25.5, economyRate: 5.8, bestBowling: '4/21', catches: 22, stumpings: 0 },
      ['13 Wickets in 2019 ICC World Cup including 51* vs India in Birmingham', 'Toe-Crushing Yorker Bowler in Death Overs']),

    p('ban_nurul_hasan_sohan', 'Nurul Hasan Sohan', 'Nurul Hasan Sohan', 'Bangladesh', 'BAN', 30, '1993-11-21', 'Active', 'STAR', 68, 'Wicketkeeper-Batter', 'Master Gloveman & Captain', 'Right-hand bat', 'Right-arm off break',
      { battingAbility: 78, technique: 76, timing: 80, power: 82, shotSelection: 78, strikeRotation: 82, runningBetweenWickets: 88 },
      { bowlingAbility: 10, pace: 20, accuracy: 15, swing: 10, seam: 10, spin: 15, variation: 15, control: 15 },
      { fielding: 96, catching: 98, throwing: 92, groundFielding: 94, reaction: 98 },
      { wicketkeeping: 98, catching: 98, stumping: 98, reflexes: 98 },
      'Rangpur Riders (Captain)', 'Bangladesh Premier League', 2000, 400,
      { matches: 82, runs: 1250, highestScore: 64, battingAverage: 23.0, strikeRate: 118.0, hundreds: 0, fifties: 4, wickets: 0, bowlingAverage: 0, economyRate: 0, bestBowling: '0/0', catches: 95, stumpings: 32 },
      ['Acknowledged as the most technically gifted Wicketkeeper in Bangladesh History', 'Captain of Rangpur Riders in BPL']),

    p('ban_mosaddek_hossain_saikat', 'Mosaddek Hossain Saikat', 'Mosaddek Hossain', 'Bangladesh', 'BAN', 28, '1995-12-10', 'Active', 'STAR', 68, 'All-Rounder', 'Off Spin All-Rounder & Finisher', 'Right-hand bat', 'Right-arm off break',
      { battingAbility: 80, technique: 80, timing: 84, power: 86, shotSelection: 80, strikeRotation: 82, runningBetweenWickets: 86 },
      { bowlingAbility: 76, pace: 48, accuracy: 82, swing: 15, seam: 15, spin: 78, variation: 74, control: 82 },
      { fielding: 88, catching: 92, throwing: 88, groundFielding: 88, reaction: 90 }, null,
      'Sylhet Strikers', 'Bangladesh Premier League', 1900, 380,
      { matches: 86, runs: 1350, highestScore: 75, battingAverage: 26.0, strikeRate: 115.0, hundreds: 0, fifties: 5, wickets: 45, bowlingAverage: 30.0, economyRate: 5.4, bestBowling: '5/20', catches: 38, stumpings: 0 },
      ['Heroic 52* off 24 balls to win the 2019 Tri-Nation Final in Dublin vs West Indies (Bangladesh\'s First Multi-Nation Trophy)', '5/20 vs Zimbabwe in T20I (All in First 3 Overs)']),

    p('ban_habibul_bashar', 'Habibul Bashar', 'Habibul Bashar (Mr. Fifty)', 'Bangladesh', 'BAN', 52, '1972-08-17', 'Retired', 'STAR', 70, 'Batter', 'Historic Captain & Top-Order Pioneer', 'Right-hand bat', 'Right-arm off break',
      { battingAbility: 84, technique: 86, timing: 86, power: 74, shotSelection: 86, strikeRotation: 82, runningBetweenWickets: 80 },
      { bowlingAbility: 25, pace: 35, accuracy: 30, swing: 20, seam: 20, spin: 30, variation: 25, control: 30 },
      { fielding: 84, catching: 88, throwing: 82, groundFielding: 82, reaction: 85 }, null,
      'Bangladesh Legend', 'National', 2200, 440,
      { matches: 161, runs: 5193, highestScore: 113, battingAverage: 28.5, strikeRate: 68.0, hundreds: 3, fifties: 38, wickets: 1, bowlingAverage: 55.0, economyRate: 5.0, bestBowling: '1/11', catches: 61, stumpings: 0 },
      ['Captain who led Bangladesh to historic victories over Australia (Cardiff 2005) & India/South Africa (2007 World Cup)', '"Mr. Fifty" — Founded Bangladesh\'s batting backbone in early Test era']),

    p('ban_mohammad_ashraful', 'Mohammad Ashraful', 'Mohammad Ashraful (Matador)', 'Bangladesh', 'BAN', 40, '1984-07-07', 'Retired', 'STAR', 70, 'Batter', 'Prodigious Stroke Maker', 'Right-hand bat', 'Right-arm leg break',
      { battingAbility: 88, technique: 82, timing: 96, power: 84, shotSelection: 78, strikeRotation: 82, runningBetweenWickets: 85 },
      { bowlingAbility: 65, pace: 45, accuracy: 70, swing: 20, seam: 20, spin: 74, variation: 75, control: 70 },
      { fielding: 86, catching: 90, throwing: 86, groundFielding: 86, reaction: 88 }, null,
      'Dhaka Gladiators Legend', 'Bangladesh Premier League', 2400, 480,
      { matches: 261, runs: 6655, highestScore: 190, battingAverage: 24.5, strikeRate: 75.0, hundreds: 9, fifties: 30, wickets: 47, bowlingAverage: 45.0, economyRate: 5.1, bestBowling: '3/26', catches: 60, stumpings: 0 },
      ['Youngest Player in Cricket History to score a Test Century (114 vs Sri Lanka at age 17 in 2001)', 'Sensational 100 vs Australia in Cardiff 2005 & 61 off 27 vs West Indies in 2007 T20 World Cup', '190 vs Sri Lanka in Galle Test 2013']),

    p('ban_abdur_razzak', 'Abdur Razzak', 'Abdur Razzak (King of Spin)', 'Bangladesh', 'BAN', 42, '1982-06-15', 'Retired', 'STAR', 70, 'Bowler', 'Left-Arm Finger Spin Maestro', 'Left-hand bat', 'Slow left-arm orthodox',
      { battingAbility: 42, technique: 35, timing: 42, power: 70, shotSelection: 38, strikeRotation: 40, runningBetweenWickets: 60 },
      { bowlingAbility: 88, pace: 48, accuracy: 96, swing: 15, seam: 15, spin: 92, variation: 88, control: 96 },
      { fielding: 82, catching: 85, throwing: 84, groundFielding: 82, reaction: 84 }, null,
      'Royal Challengers Bangalore (Ex)', 'Bangladesh Premier League', 2300, 460,
      { matches: 200, runs: 1250, highestScore: 53, battingAverage: 12.0, strikeRate: 85.0, hundreds: 0, fifties: 1, wickets: 279, bowlingAverage: 29.2, economyRate: 4.5, bestBowling: '5/29', catches: 42, stumpings: 0 },
      ['First Bangladeshi Bowler to reach 200 ODI Wickets (207 wickets in 153 matches)', 'Four 5-Wicket Hauls in ODIs including a Hat-trick vs Zimbabwe in 2010', 'National Team Selector & Legend']),

    p('ban_shahriar_nafees', 'Shahriar Nafees', 'Shahriar Nafees', 'Bangladesh', 'BAN', 38, '1985-05-01', 'Retired', 'STAR', 68, 'Batter', 'Classical Left-Handed Opener', 'Left-hand bat', 'Right-arm slow',
      { battingAbility: 82, technique: 86, timing: 86, power: 78, shotSelection: 84, strikeRotation: 82, runningBetweenWickets: 82 },
      { bowlingAbility: 10, pace: 20, accuracy: 15, swing: 10, seam: 10, spin: 15, variation: 15, control: 15 },
      { fielding: 84, catching: 88, throwing: 82, groundFielding: 84, reaction: 85 }, null,
      'Barisal Burners (Inaugural BPL Finalist Captain)', 'Bangladesh Premier League', 1800, 360,
      { matches: 100, runs: 3500, highestScore: 138, battingAverage: 32.0, strikeRate: 72.0, hundreds: 5, fifties: 20, wickets: 0, bowlingAverage: 0, economyRate: 0, bestBowling: '0/0', catches: 35, stumpings: 0 },
      ['First Bangladeshi to score 1,000+ ODI runs in a calendar year (1,033 runs with 4 centuries in 2006)', '138 vs Australia in Fatullah Test 2006']),

    p('ban_rubel_hossain', 'Rubel Hossain', 'Rubel Hossain (Malinga Action)', 'Bangladesh', 'BAN', 34, '1990-01-01', 'Active', 'STAR', 69, 'Bowler', 'Slingy Fast Bowler & 2015 WC Adelaide Hero', 'Right-hand bat', 'Right-arm fast',
      { battingAbility: 25, technique: 20, timing: 25, power: 55, shotSelection: 22, strikeRotation: 25, runningBetweenWickets: 60 },
      { bowlingAbility: 86, pace: 94, accuracy: 82, swing: 88, seam: 86, spin: 10, variation: 88, control: 82 },
      { fielding: 82, catching: 85, throwing: 88, groundFielding: 82, reaction: 85 }, null,
      'Khulna Tigers', 'Bangladesh Premier League', 2200, 440,
      { matches: 159, runs: 380, highestScore: 21, battingAverage: 7.0, strikeRate: 65.0, hundreds: 0, fifties: 0, wickets: 192, bowlingAverage: 34.0, economyRate: 5.6, bestBowling: '6/26', catches: 30, stumpings: 0 },
      ['Historic Adelaide 2015 World Cup Knockout of England (4/53 — Clean bowled Broad and Anderson in 49th over)', 'ODI Hat-trick & 6/26 vs New Zealand in 2013', '145+ km/h Slingy Reverse Swing Yorker Master'])
  ];

  writeCountry('bangladesh.ts', 'BANGLADESH_PLAYERS', BAN_PLAYERS);
}

generateNations();
console.log('Bangladesh complete with 35 players.');
